# Podfile
use_frameworks!

target 'example-rxswift' do
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'example-rxswiftUITests' do
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end
